import fs from 'node:fs';
import path from 'node:path';
import {analyticsProvider,configuredOutcomeEvents} from './analytics.js';
import {candidates,comparisonReadiness,config,normalize,periods,queryChanges,reportReadiness,snapshotId,Store,validWindowDays} from './core.js';
import {gsc,pageSegments,queryExamples,queryPageRows} from './google.js';
import {internalLinkContext,pageSourceContext,repositoryContext} from './context.js';

function withReadiness(snapshot:any,c:any){
  const gscTruncated=Boolean(snapshot.coverage?.gscTruncated);
  const readiness=comparisonReadiness(c,gscTruncated,{current:snapshot.analytics?.current,previous:snapshot.analytics?.previous},snapshot.createdAt);
  return {...snapshot,coverage:{...snapshot.coverage,gscTruncated,readiness}};
}

function periodDays(period:any){return period?.start&&period?.end?Math.round((Date.parse(`${period.end}T00:00:00Z`)-Date.parse(`${period.start}T00:00:00Z`))/86400000)+1:0}
function pageRow(snapshot:any,key:string,c:any){return snapshot.gsc?.find((row:any)=>(row.key||normalize(row.url,c))===key)||null}
function observation(row:any,snapshot:any,id:string,createdAt:string,c:any){return{snapshotId:id,createdAt:snapshot.createdAt||createdAt,period:snapshot.range.current,windowDays:periodDays(snapshot.range.current),performance:row,readiness:withReadiness(snapshot,c).coverage.readiness}}
export function queryCoverage(rows:any[],page:any,limit:number){const subtotal=rows.reduce((sum,row)=>({clicks:sum.clicks+row.clicks,impressions:sum.impressions+row.impressions}),{clicks:0,impressions:0}),total={clicks:page?.clicks||0,impressions:page?.impressions||0};return{displayedRowLimit:limit,displayedRows:rows.length,displayed:subtotal,pageTotal:total,differenceNotExplainedByDisplayedRows:{clicks:total.clicks-subtotal.clicks,impressions:total.impressions-subtotal.impressions}}}

export async function sync(refresh=false,windowDays=30){
  if(!validWindowDays(windowDays))throw Error('windowDays must be one of 30, 60, or 90.');const c=config(),store=new Store(c.dataDir),range=periods(c.lag,windowDays),id=snapshotId(c,range.current),saved=store.get(id);
  if(saved&&!refresh){const snapshot=withReadiness(saved,c);if(!saved.coverage?.readiness)store.save(id,snapshot);return{id,cached:true,...snapshot}}
  const provider=analyticsProvider(c),[a,b,analyticsNow,analyticsBefore]=await Promise.all([gsc(c,range.current),gsc(c,range.previous),provider.landingEvidence(range.current),provider.landingEvidence(range.previous)]);
  const enrich=(rows:any[])=>rows.map(row=>({...row,key:normalize(row.url,c)}));
  const createdAt=new Date().toISOString();
  const snapshot=withReadiness({profile:c.profile,analyticsProvider:c.analyticsProvider,range,gsc:enrich(a.rows),previousGsc:enrich(b.rows),analytics:{current:{...analyticsNow,rows:enrich(analyticsNow.rows)},previous:{...analyticsBefore,rows:enrich(analyticsBefore.rows)}},coverage:{gscTruncated:a.truncated||b.truncated,notes:['GSC returns top rows; query evidence is not attributed to analytics visits, sessions, or conversions.'],gsc:{rowCap:c.cap,currentTruncated:a.truncated,previousTruncated:b.truncated},analytics:{provider:c.analyticsProvider,current:analyticsNow.coverage,previous:analyticsBefore.coverage}},createdAt},c);
  store.save(id,snapshot);return{id,cached:false,...snapshot};
}

export async function pageContext(url:string,snapshotIdValue?:string,limit=5,windowDays=30){
  const c=config(),store=new Store(c.dataDir),raw=snapshotIdValue?store.get(snapshotIdValue):await sync(false,windowDays);
  if(!raw)throw Error(`No local snapshot found for ${snapshotIdValue}.`);
  if(raw.profile&&raw.profile!==c.profile)throw Error(`Snapshot ${snapshotIdValue} belongs to profile ${raw.profile}, not ${c.profile}.`);
  const r=withReadiness(raw,c),key=normalize(url,c),page=r.gsc.find((row:any)=>row.key===key)||r.previousGsc.find((row:any)=>row.key===key);
  if(!page)throw Error(`No page-level GSC row found for ${url} in this snapshot.`);
  const [current,previous]=await Promise.all([queryExamples(c,r.range.current,page.url,limit),queryExamples(c,r.range.previous,page.url,limit)]);
  const currentPage=r.gsc.find((row:any)=>row.key===key)||null,prior=r.previousGsc.find((row:any)=>row.key===key),operationalAnnotations=store.actions().filter((action:any)=>action.implementation_date&&action.implementation_date>=r.range.previous.start&&action.implementation_date<=r.range.current.end&&normalize(action.url,c)===key);return{profile:c.profile,analyticsProvider:r.analyticsProvider||c.analyticsProvider,snapshotId:snapshotIdValue||r.id,url:page.url,periods:r.range,windowDays,decisionReadiness:prior&&prior.impressions>=c.minimumBaselineImpressions?r.coverage.readiness:{state:'maturing',reasons:[`Prior period has fewer than ${c.minimumBaselineImpressions} impressions.`],reportingLagDays:c.lag},pagePerformance:{current:currentPage,previous:prior||null},operationalAnnotations,analyticsEvidence:{metricLabels:r.analytics.current.metricLabels,current:r.analytics.current.rows.filter((row:any)=>row.key===key),previous:r.analytics.previous.rows.filter((row:any)=>row.key===key),sourceSummaries:{current:r.analytics.current.sourceSummaries,previous:r.analytics.previous.sourceSummaries},coverage:{current:r.analytics.current.coverage,previous:r.analytics.previous.coverage}},queryEvidence:{current,previous,changes:queryChanges(current,previous),coverage:{current:queryCoverage(current,currentPage,limit),previous:queryCoverage(previous,prior,limit)},limitation:'Examples are limited top GSC rows, not complete coverage, and are not attributed to analytics visits, sessions, or conversions. Differences from page totals are not asserted to be privacy-withheld or absent.'}};
}

export async function pageInvestigationContext(url:string,windowDays=30,question?:string){const page:any=await pageContext(url,undefined,10,windowDays),terms=question?[question]:[...page.queryEvidence.current,...page.queryEvidence.previous].map((row:any)=>row.query);return{...page,sourceContext:await pageSourceContext(page.url,terms),limitation:'This response combines source-scoped GSC and GA4 evidence with bounded local source context. It does not determine answer quality, attribute analytics to queries, or recommend an edit.'}}
export async function questionPageContext(url:string,question:string,windowDays=90){const context=await pageInvestigationContext(url,windowDays,question);return{...context,question,limitation:'The question and local source context are evidence for a chat client. The client decides whether the answer is already present, buried, weak, or missing and whether to propose a change.'}}

export async function pageSegmentContext(url:string,dimension:'country'|'device'|'searchAppearance',limit=10,windowDays=30){const context:any=await pageContext(url,undefined,1,windowDays),c=config(),[current,previous]=await Promise.all([pageSegments(c,context.periods.current,context.url,dimension,limit),pageSegments(c,context.periods.previous,context.url,dimension,limit)]),before=new Map(previous.map(x=>[x.value,x]));return{...context,segmentEvidence:{dimension,current,previous,changes:current.map(x=>({value:x.value,current:x,previous:before.get(x.value)||null,clickChange:x.clicks-(before.get(x.value)?.clicks||0),impressionChange:x.impressions-(before.get(x.value)?.impressions||0)})),limitation:'Segment rows are bounded top GSC rows and do not prove cause.'}}}
export async function pageBrief(url:string,windowDays=30){const x:any=await pageContext(url,undefined,5,windowDays),a=x.pagePerformance.current,b=x.pagePerformance.previous,change=(a?.clicks||0)-(b?.clicks||0),action=x.decisionReadiness.state==='maturing'?'monitor':'investigate';return{...x,brief:{observed:[`Clicks: ${b?.clicks??0} → ${a?.clicks??0}`,`Impressions: ${b?.impressions??0} → ${a?.impressions??0}`,`Position: ${b?.position?.toFixed?.(1)??'n/a'} → ${a?.position?.toFixed?.(1)??'n/a'}`],whatItMayMean:change<0?'Search visibility declined; inspect query mix and page intent before changing copy.':'No decline diagnosis is implied; inspect the observed movement before acting.',limitations:[...x.decisionReadiness.reasons,x.queryEvidence.limitation],checklist:[change<0?'Check whether the opening answers the falling query theme.':'Check what is driving the observed query growth before changing the page.','Check reader intent and existing contextual links.','Confirm the page source and implementation scope before editing.'],nextCheck:'Inspect the query movement and current opening together.',recommendedAction:action}}}
export async function pageLifecycle(url:string){const c=config(),key=normalize(url,c),windows=[30,60,90],snapshots=await Promise.all(windows.map(days=>sync(false,days)));const evidence=snapshots.map((snapshot:any,idx)=>{const current=snapshot.gsc.find((row:any)=>row.key===key),previous=snapshot.previousGsc.find((row:any)=>row.key===key),baseline=previous?.impressions||0;return{windowDays:windows[idx],snapshotId:snapshot.id,current:current||null,previous:previous||null,clickChange:(current?.clicks||0)-(previous?.clicks||0),impressionChange:(current?.impressions||0)-baseline,maturity:baseline<c.minimumBaselineImpressions?'maturing':'established',readiness:snapshot.coverage.readiness}});const established=evidence.filter(x=>x.maturity==='established'),declines=established.filter(x=>x.clickChange<0).length,growth=established.filter(x=>x.clickChange>0).length;return{url,windows:evidence,flags:{repeatedDecline:declines>=2,repeatedGrowth:growth>=2,maturing:evidence.every(x=>x.maturity==='maturing'),insufficientEvidence:!established.length},limitation:'Flags are deterministic summaries of selected windows, not predictions or recommendations.'}}
export function pageHistory(url:string,windowDays=30,limit=6){
  if(!validWindowDays(windowDays))throw Error('windowDays must be one of 30, 60, or 90.');
  if(!Number.isInteger(limit)||limit<1||limit>12)throw Error('limit must be a whole number from 1 to 12.');
  const c=config(),store=new Store(c.dataDir),key=normalize(url,c),storedSnapshots=store.snapshots();
  const observations=storedSnapshots.filter((item:any)=>item.payload.profile===c.profile&&(item.payload.analyticsProvider||c.analyticsProvider)===c.analyticsProvider&&periodDays(item.payload.range?.current)===windowDays).map((item:any)=>{const row=pageRow(item.payload,key,c);return row?observation(row,item.payload,item.id,item.createdAt,c):null}).filter(Boolean).sort((a:any,b:any)=>b.period.end.localeCompare(a.period.end)).slice(0,limit);
  const annotations=store.actions().filter((action:any)=>normalize(action.url,c)===key);
  return{profile:c.profile,analyticsProvider:c.analyticsProvider,url,windowDays,observations,annotations,coverage:{storedSnapshotsInspected:storedSnapshots.length,observationsReturned:observations.length},limitation:'History contains only locally stored snapshots with matching profile, analytics provider, and comparison window. Missing observations are not backfilled, and the client decides whether movement is a trend or ordinary variation.'};
}
export async function queryEntryExit(url:string,windowDays=30,limit=20){const x:any=await pageContext(url,undefined,limit,windowDays),changes=x.queryEvidence.changes;return{url:x.url,windowDays,periods:x.periods,entered:changes.filter((q:any)=>q.previous.impressions===0&&q.current.impressions>0),exited:changes.filter((q:any)=>q.current.impressions===0&&q.previous.impressions>0),retained:changes.filter((q:any)=>q.previous.impressions>0&&q.current.impressions>0),limitation:x.queryEvidence.limitation}}
export function questionLikeRule(query:string){const text=query.trim().toLocaleLowerCase();const danish=/^(hvad|hvordan|hvorfor|hvor|hvornår|hvem|hvilken|hvilket|hvilke|kan|skal|er|har|må|vil|bliver)\b/u.exec(text);if(danish)return`Danish question pattern: ${danish[1]}`;const english=/^(what|how|why|where|when|who|which|can|should|is|are|does|do|will)\b/u.exec(text);if(english)return`English question pattern: ${english[1]}`;if(/\b(how to|what is|hvad er|hvordan kan|kan man|skal man)\b/u.test(text))return'Conversational question phrase';return null}
export function questionOpportunityCandidates(currentRows:any[],previousRows:any[],limit=30){const key=(row:any)=>`${row.query}\u0000${row.url}`,before=new Map(previousRows.map(row=>[key(row),row])),now=new Map(currentRows.map(row=>[key(row),row])),zero=(query:string,url:string)=>({query,url,clicks:0,impressions:0,ctr:0,position:0});return[...new Set([...now.keys(),...before.keys()])].map(id=>{const currentRow=now.get(id),previousRow=before.get(id),row=currentRow||previousRow!,matchRule=questionLikeRule(row.query);if(!matchRule)return null;const a=currentRow||zero(row.query,row.url),b=previousRow||zero(row.query,row.url);return{query:row.query,url:row.url,matchRule,current:a,previous:b,state:a.impressions>0&&b.impressions===0?'entered':a.impressions===0&&b.impressions>0?'exited':'retained',clickChange:a.clicks-b.clicks,impressionChange:a.impressions-b.impressions,positionChange:a.impressions>0&&b.impressions>0?a.position-b.position:null}}).filter(Boolean).sort((a:any,b:any)=>Math.max(b.current.impressions,b.previous.impressions)-Math.max(a.current.impressions,a.previous.impressions)||Math.abs(b.impressionChange)-Math.abs(a.impressionChange)).slice(0,limit)}
export async function findQuestionOpportunities(windowDays=90,limit=30){if(!validWindowDays(windowDays))throw Error('windowDays must be one of 30, 60, or 90.');if(!Number.isInteger(limit)||limit<1||limit>100)throw Error('limit must be a whole number from 1 to 100.');const c=config(),range=periods(c.lag,windowDays),[current,previous]=await Promise.all([queryPageRows(c,range.current),queryPageRows(c,range.previous)]);return{profile:c.profile,windowDays,periods:range,queryCandidates:questionOpportunityCandidates(current.rows,previous.rows,limit),coverage:{rowLimit:c.cap,currentTruncated:current.truncated,previousTruncated:previous.truncated},limitation:'Question-like query candidates use deterministic Danish and English text patterns. GSC query-and-page rows are bounded top rows, may omit low-volume data, and cannot show whether the same question was asked in an LLM or answer engine. Rows are evidence, not content recommendations.'}}
export function actionLog(url?:string){const store=new Store(config().dataDir);return{actions:store.actions(url),dueForReview:store.due()}}
export function recordAction(input:any){const store=new Store(config().dataDir);return{actionId:store.action(input)}}
export function actionReviewContext(actionId:string){
  const c=config(),store=new Store(c.dataDir),action:any=store.actionById(actionId);
  if(!action)throw Error(`No local action found for ${actionId}.`);
  const implementationDate=action.implementation_date||'',explicit=action.baseline_snapshot?store.get(action.baseline_snapshot):null,explicitWindow=periodDays(explicit?.range?.current),windowDays=validWindowDays(explicitWindow)?explicitWindow:30,history:any=pageHistory(action.url,windowDays,12),observations=history.observations;
  const explicitBaseline=explicit?observations.find((item:any)=>item.snapshotId===action.baseline_snapshot)||(()=>{const key=normalize(action.url,c),row=pageRow(explicit,key,c);return row?observation(row,explicit,action.baseline_snapshot,explicit.createdAt||'',c):null})():null;
  const baseline=explicitBaseline||observations.find((item:any)=>!implementationDate||item.period.end<implementationDate)||null;
  const after=implementationDate?observations.find((item:any)=>item.period.start>implementationDate)||null:null;
  const overlapping=implementationDate?observations.find((item:any)=>item.period.start<=implementationDate&&item.period.end>=implementationDate)||null:null;
  const today=new Date().toISOString().slice(0,10),reviewDue=Boolean(action.review_date&&action.review_date<=today&&!['Reviewed','Dismissed'].includes(action.status));
  const gaps=[];if(!implementationDate)gaps.push('No implementation date is recorded.');if(!baseline)gaps.push('No comparable baseline snapshot is stored.');if(implementationDate&&!after)gaps.push('No clean post-implementation snapshot is stored yet.');
  return{profile:c.profile,analyticsProvider:c.analyticsProvider,action,reviewDue,windowDays,evidence:{baseline,after,overlapping},gaps,limitation:'Before/after observations are retrieval evidence only. They do not establish that the recorded action caused a measured change.'};
}
export async function measurementReadiness(){const r:any=await sync(),c=config(),rows=[...r.analytics.current.rows,...r.analytics.previous.rows],sources=rows.map((x:any)=>x.acquisition?.value||''),outcomes=await configuredOutcomeEvents(c,r.range.current);return{profile:r.profile,provider:r.analyticsProvider,lenses:{googleOrganic:sources.some((x:string)=>x.toLowerCase().includes('google / organic')),allOrganic:sources.some((x:string)=>x.toLowerCase().includes('/ organic')),identifiableAiReferrals:sources.filter((x:string)=>/(chatgpt|perplexity|claude|gemini)/i.test(x))},configuredOutcomes:outcomes,gaps:outcomes.available?[]:['Configure GA4_OUTCOME_EVENT_NAMES to inspect explicitly named GA4 events.'],limitations:['Source labels and outcome events remain provider-scoped and are not query-attributed.']}}
export async function pageRepositoryContext(url:string){return repositoryContext(url)}
export async function pageInternalLinkContext(url:string){const x:any=await pageContext(url,undefined,10);return internalLinkContext(url,x.queryEvidence.current.map((q:any)=>q.query))}

export async function report(refresh=false,windowDays=30){
  const r=await sync(refresh,windowDays),c=config(),list=candidates(r.gsc,r.previousGsc,r.coverage.readiness,c),readiness=reportReadiness(r.coverage.readiness,list.length);
  fs.mkdirSync(c.reportDir,{recursive:true,mode:0o700});
  const details=await Promise.all(list.slice(0,3).map(async candidate=>{try{return await pageContext(candidate.url,r.id,5)}catch(error){return{url:candidate.url,error:error instanceof Error?error.message:String(error)}}}));
  const lines=['# Site Signal report','',`Profile: \`${r.profile}\``, `Analytics provider: \`${r.analyticsProvider}\``, `Snapshot: \`${r.id}\` (${r.cached?'cached':'fresh'})`,'',`Periods: ${r.range.current.start}–${r.range.current.end} versus ${r.range.previous.start}–${r.range.previous.end}.`,'','## Evidence readiness','',`- State: ${readiness.state}`,`- Reporting lag: ${readiness.reportingLagDays} complete days`,...readiness.reasons.map((reason:string)=>`- Reason: ${reason}`),'','## Evidence-backed investigations',''];
  if(!list.length)lines.push('No candidate met the configured review gates. This is an insufficient-evidence result, not a recommendation to change content.');
  for(const [index,candidate]of list.slice(0,10).entries()){
    lines.push(`### ${candidate.url}`,'',`- Decision readiness: ${candidate.decisionReadiness?.state||'incomplete_coverage'}`,...(candidate.decisionReadiness?.reasons||['Snapshot readiness is unavailable; refresh the snapshot before acting.']).map((reason:string)=>`- Readiness reason: ${reason}`),`- Click change: ${candidate.clickChange}`,`- Impression change: ${candidate.impressionChange}`,`- Position change: ${candidate.positionChange.toFixed(1)}`);
    const detail=details[index] as any;
    if(detail?.queryEvidence?.changes?.length)lines.push('- Query examples with the largest observed movement:',...detail.queryEvidence.changes.slice(0,5).map((query:any)=>`  - ${query.query}: clicks ${query.previous.clicks} → ${query.current.clicks}; impressions ${query.previous.impressions} → ${query.current.impressions}; position ${query.baseline==='comparable'?`${query.previous.position.toFixed(1)} → ${query.current.position.toFixed(1)}`:'new/no baseline'}`));
    lines.push('- Limitation: query examples are top returned GSC rows, not complete coverage, and are not attributed to analytics visits, sessions, or conversions.','');
  }
  const out=path.join(c.reportDir,`report-${r.id}.md`),payload={profile:r.profile,analyticsProvider:r.analyticsProvider,snapshotId:r.id,decisionReadiness:readiness,coverage:r.coverage,candidates:list,details};
  fs.writeFileSync(out,lines.join('\n'));fs.writeFileSync(out.replace('.md','.json'),JSON.stringify(payload,null,2));
  return{profile:r.profile,analyticsProvider:r.analyticsProvider,path:out,snapshotId:r.id,decisionReadiness:readiness,candidates:list.length};
}

export async function status(){
  const c=config(),providerMissing=c.analyticsProvider==='ga4'?['ga4PropertyId']:c.analyticsProvider==='matomo'?['matomoUrl','matomoSiteId','matomoTokenAuth']:[],missing=['domain','gscProperty',...providerMissing].filter(key=>!c[key as keyof typeof c]),capabilities=missing.length?[]:analyticsProvider(c).capabilities();
  const optionalCapabilities={repository:{configured:Boolean(c.repositoryPath),reason:c.repositoryPath?'Local repository path is configured.':'SITE_SIGNAL_REPOSITORY_PATH is not configured.'},sitemap:{configured:Boolean(c.sitemapUrl),reason:c.sitemapUrl?'Sitemap URL is configured.':'SITE_SIGNAL_SITEMAP_URL is not configured.'},outcomeEvents:{configured:c.outcomeEvents.length>0,reason:c.outcomeEvents.length?`${c.outcomeEvents.length} outcome event name(s) configured.`:c.analyticsProvider==='ga4'?'GA4_OUTCOME_EVENT_NAMES is not configured.':'Configured outcome events are currently supported for GA4 only.'},analytics:{configured:c.analyticsProvider!=='none',reason:c.analyticsProvider==='none'?'No analytics provider is selected; GSC-only mode remains available.':`${c.analyticsProvider} is selected.`}};
  return{profile:c.profile,analyticsProvider:c.analyticsProvider,configured:!missing.length,missingSetup:missing,optionalCapabilities,dataDir:c.dataDir,reportingLagDays:c.lag,capabilities:['read-only GSC page data',...capabilities,'local reports and snapshots','stdio MCP']};
}
